/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JAplFEFIT.java
 *
 * Created on 13/07/2009, 00:56:05
 */

package com.rimisan.applets.fefit.ui;

import com.rimisan.applets.fefit.FEFITApp;
import com.rimisan.file.FileScanner;
import com.rimisan.file.IFileFilter;
import com.rimisan.file.IFileScannerEventListener;
import com.rimisan.file.JavascriptExposedFileFilter;
import com.rimisan.file.RegExpNameFileFilter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.Invocable;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JApplet;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;




/**
 *
 * @author Glauco
 */
public class JAplFEFIT extends javax.swing.JFrame implements Runnable, IFileScannerEventListener{
    StringBuilder sb = null;
    JFrame me = this;
    javax.script.ScriptEngineManager sce = new ScriptEngineManager();
    ScriptEngine se = sce.getEngineByName("javascript");

    public static void main(String[] args) {
      Runnable r = new Runnable() {
         public void run() {
            JFrame f = new JAplFEFIT();//new JFrame("FEFIT");
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //f.add();
            f.pack();
            f.setLocationByPlatform(true);
            f.setVisible(true);
        }
      };
      SwingUtilities.invokeLater(r);
   }
    public JAplFEFIT()
    {
        initComponents();
    }
     /** Initializes the applet JAplFEFIT */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcaoAcao = new javax.swing.ButtonGroup();
        buttonGroupTipoFiltro = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        cmdEscolheDiretorio = new javax.swing.JButton();
        txtDiretorioRaiz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdIniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPaneResultado = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbQtdPastas = new javax.swing.JLabel();
        jlbQtdArquivos = new javax.swing.JLabel();
        jlbQtdOcorrencias = new javax.swing.JLabel();
        jRadioButtonAcaoSubst = new javax.swing.JRadioButton();
        jRadioButtonAcaoJavascript = new javax.swing.JRadioButton();
        jRadioButtonFiltroJavascript = new javax.swing.JRadioButton();
        jRadioButtonFiltroRegExp = new javax.swing.JRadioButton();
        jCheckBoxCoincidirCaminhoCompleto = new javax.swing.JCheckBox();
        jCheckBoxSomenteDiretorios = new javax.swing.JCheckBox();
        cmdEscolheDiretorio1 = new javax.swing.JButton();
        cmdEscolheDiretorio2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCriterio = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcao = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        cmdEscolheDiretorio.setText("...");
        cmdEscolheDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEscolheDiretorioActionPerformed(evt);
            }
        });

        txtDiretorioRaiz.setText(".");
        txtDiretorioRaiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDiretorioRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiretorioRaizMouseClicked(evt);
            }
        });

        jLabel1.setText("Diretório raiz da procura:");

        jLabel2.setText("Critério de procura:");

        jLabel4.setText("Ação sobre coincidências:");

        cmdIniciar.setText("Iniciar");
        cmdIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIniciarActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultado:");

        jEditorPaneResultado.setEditorKit(new javax.swing.text.html.HTMLEditorKit());
        jScrollPane2.setViewportView(jEditorPaneResultado);

        jButton1.setText("Salvar resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar resultado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Pastas percorridas:");

        jLabel7.setText("Arquivos percorridos:");

        jLabel8.setText("Ocorrências que satisfazem o critério:");

        jlbQtdPastas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbQtdPastas.setText("0");
        jlbQtdPastas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbQtdArquivos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbQtdArquivos.setText("0");
        jlbQtdArquivos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jlbQtdOcorrencias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbQtdOcorrencias.setText("0");
        jlbQtdOcorrencias.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(jlbQtdPastas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jlbQtdOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbQtdArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jlbQtdArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jlbQtdPastas)
                        .addComponent(jLabel8)
                        .addComponent(jlbQtdOcorrencias)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        buttonGroupOpcaoAcao.add(jRadioButtonAcaoSubst);
        jRadioButtonAcaoSubst.setSelected(true);
        jRadioButtonAcaoSubst.setText("Substituição");
        jRadioButtonAcaoSubst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAcaoSubstActionPerformed(evt);
            }
        });

        buttonGroupOpcaoAcao.add(jRadioButtonAcaoJavascript);
        jRadioButtonAcaoJavascript.setText("Javascript");
        jRadioButtonAcaoJavascript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAcaoJavascriptActionPerformed(evt);
            }
        });

        buttonGroupTipoFiltro.add(jRadioButtonFiltroJavascript);
        jRadioButtonFiltroJavascript.setText("Javascript");
        jRadioButtonFiltroJavascript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFiltroJavascriptActionPerformed(evt);
            }
        });

        buttonGroupTipoFiltro.add(jRadioButtonFiltroRegExp);
        jRadioButtonFiltroRegExp.setSelected(true);
        jRadioButtonFiltroRegExp.setText("Expressão Regular");
        jRadioButtonFiltroRegExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFiltroRegExpActionPerformed(evt);
            }
        });

        jCheckBoxCoincidirCaminhoCompleto.setText("Concidir caminho inteiro");
        jCheckBoxCoincidirCaminhoCompleto.setToolTipText("Quando desmarcado o critério é avaliado somente sobre nome do arquivo.");
        jCheckBoxCoincidirCaminhoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoincidirCaminhoCompletoActionPerformed(evt);
            }
        });

        jCheckBoxSomenteDiretorios.setText("Percorrer somente diretórios.");
        jCheckBoxSomenteDiretorios.setToolTipText("Quando desmarcado o critério é avaliado somente sobre nome do arquivo.");
        jCheckBoxSomenteDiretorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSomenteDiretoriosActionPerformed(evt);
            }
        });

        cmdEscolheDiretorio1.setText("...");
        cmdEscolheDiretorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEscolheDiretorio1ActionPerformed(evt);
            }
        });

        cmdEscolheDiretorio2.setText("...");
        cmdEscolheDiretorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEscolheDiretorio2ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCriterio.setColumns(20);
        txtCriterio.setRows(1);
        txtCriterio.setText(FEFITApp.CRITERIO_PADRAO_REGEX);
        txtCriterio.setBorder(null);
        txtCriterio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCriterioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(txtCriterio);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAcao.setColumns(20);
        txtAcao.setRows(1);
        txtAcao.setText(FEFITApp.ACAO_PADRAO_SUBSTITUICAO);
        txtAcao.setBorder(null);
        txtAcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAcaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtAcao);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(jCheckBoxSomenteDiretorios)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addComponent(cmdIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDiretorioRaiz)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdEscolheDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdEscolheDiretorio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmdEscolheDiretorio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonFiltroRegExp))
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonAcaoSubst)
                                        .addComponent(jRadioButtonFiltroJavascript))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonAcaoJavascript)
                                        .addComponent(jCheckBoxCoincidirCaminhoCompleto)))
                                .addComponent(jLabel5))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jCheckBoxSomenteDiretorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(1, 1, 1)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmdEscolheDiretorio)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(txtDiretorioRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jRadioButtonFiltroJavascript)
                        .addComponent(jRadioButtonFiltroRegExp)
                        .addComponent(jCheckBoxCoincidirCaminhoCompleto))
                    .addGap(1, 1, 1)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmdEscolheDiretorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jRadioButtonAcaoSubst)
                        .addComponent(jRadioButtonAcaoJavascript))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmdEscolheDiretorio2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGap(42, 42, 42)
                    .addComponent(cmdIniciar)
                    .addGap(9, 9, 9)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGap(100, 100, 100)))
        );

        jLabel4.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem1");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem1");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAcaoMouseClicked
        if(isRightDoubleClick(evt)){
            LancarEditorDeAcao();
        }
    }//GEN-LAST:event_txtAcaoMouseClicked

    private void txtCriterioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCriterioMouseClicked
        if(isRightDoubleClick(evt)){
            LancarEditorDeCriterio();
        }
    }//GEN-LAST:event_txtCriterioMouseClicked

    private void cmdEscolheDiretorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEscolheDiretorio2ActionPerformed
        LancarEditorDeAcao();
    }//GEN-LAST:event_cmdEscolheDiretorio2ActionPerformed

    private void cmdEscolheDiretorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEscolheDiretorio1ActionPerformed
        LancarEditorDeCriterio();
    }//GEN-LAST:event_cmdEscolheDiretorio1ActionPerformed

    private void jCheckBoxSomenteDiretoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSomenteDiretoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSomenteDiretoriosActionPerformed

    private void jCheckBoxCoincidirCaminhoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoincidirCaminhoCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCoincidirCaminhoCompletoActionPerformed

    private void jRadioButtonFiltroRegExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroRegExpActionPerformed
        if(txtCriterio.getText().equals(FEFITApp.CRITERIO_PADRAO_JAVASCRIPT))
        {
            txtCriterio.setText(FEFITApp.CRITERIO_PADRAO_REGEX);
        }
        jCheckBoxCoincidirCaminhoCompleto.setVisible(true);
    }//GEN-LAST:event_jRadioButtonFiltroRegExpActionPerformed

    private void jRadioButtonFiltroJavascriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroJavascriptActionPerformed
        if(txtCriterio.getText().equals(FEFITApp.CRITERIO_PADRAO_REGEX))
        {
            txtCriterio.setText(FEFITApp.CRITERIO_PADRAO_JAVASCRIPT);

        }

        jCheckBoxCoincidirCaminhoCompleto.setVisible(false);
    }//GEN-LAST:event_jRadioButtonFiltroJavascriptActionPerformed

    private void jRadioButtonAcaoJavascriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAcaoJavascriptActionPerformed
        if(txtAcao.getText().equals(FEFITApp.ACAO_PADRAO_SUBSTITUICAO))
        {
            txtAcao.setText(FEFITApp.ACAO_PADRAO_JAVASCRIPT);
        }
    }//GEN-LAST:event_jRadioButtonAcaoJavascriptActionPerformed

    private void jRadioButtonAcaoSubstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAcaoSubstActionPerformed
        if(txtAcao.getText().equals(FEFITApp.ACAO_PADRAO_JAVASCRIPT))
        {
            txtAcao.setText(FEFITApp.ACAO_PADRAO_SUBSTITUICAO);
        }
    }//GEN-LAST:event_jRadioButtonAcaoSubstActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jEditorPaneResultado.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogType(JFileChooser.SAVE_DIALOG);
        jfc.setAcceptAllFileFilterUsed(false);
        FileFilter ff = new FileNameExtensionFilter("Página HTML","html","htm");
        jfc.addChoosableFileFilter(ff);
        jfc.setDialogTitle("Salvar");
        jfc.showSaveDialog(this);
        String file = "";
        file = jfc.getSelectedFile().getPath() + ".html";
        FileWriter fc;
        try {
            jEditorPaneResultado.write(fc = new FileWriter(file));
            fc.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIniciarActionPerformed
        SwingWorker sw = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                IFileFilter filtro = null;
                if(jRadioButtonFiltroRegExp.isSelected())
                filtro = new RegExpNameFileFilter(txtCriterio.getText());
                else if(jRadioButtonFiltroJavascript.isSelected())
                filtro = new JavascriptExposedFileFilter(txtCriterio.getText());

                FileScanner fs = new FileScanner(new File(txtDiretorioRaiz.getText()), (IFileScannerEventListener)me,filtro);

                sb = new StringBuilder();
                jlbQtdArquivos.setText("0");
                jlbQtdOcorrencias.setText("0");
                jlbQtdPastas.setText("0");

                try{
                    fs.startScan();
                }catch(FileScanner.RootDirNotSetException e){
                    JOptionPane.showMessageDialog(null, e.toString());
                }catch(FileScanner.RootDirNotValidException ee){
                    JOptionPane.showMessageDialog(null, ee.toString());
                }

                jEditorPaneResultado.setText( "<html><body>" + sb.toString() + "</body></html>");
                return null;
            }

        };
        sw.execute();
    }//GEN-LAST:event_cmdIniciarActionPerformed

    private void txtDiretorioRaizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiretorioRaizMouseClicked
        if(isRightDoubleClick(evt))
        EscolherPasta();
    }//GEN-LAST:event_txtDiretorioRaizMouseClicked

    private void cmdEscolheDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEscolheDiretorioActionPerformed
        EscolherPasta();
    }//GEN-LAST:event_cmdEscolheDiretorioActionPerformed

    void EscolherPasta()
    {
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(JFileChooser.APPROVE_OPTION == jfc.showOpenDialog(this)){
            txtDiretorioRaiz.setText(jfc.getSelectedFile().getPath());
        }
    }
    
    void LancarEditorDeCriterio(){
        if(jRadioButtonFiltroRegExp.isSelected())
            new PopoutSimpleEditor(txtCriterio, getParentFrame(me)).setVisible(true);
        else
            (new PopoutAcaoJavascriptEditor(txtCriterio, getParentFrame(me))).setVisible(true);
    }    void LancarEditorDeAcao(){
        if(jRadioButtonAcaoSubst.isSelected())
            (new PopoutAcaoSubstEditor(txtAcao, getParentFrame(me))).setVisible(true);
        else if(jRadioButtonAcaoJavascript.isSelected())
            (new PopoutAcaoJavascriptEditor(txtAcao, getParentFrame(me))).setVisible(true);
    }    boolean isRightDoubleClick(java.awt.event.MouseEvent evt)
    {
        return evt.getClickCount() == 2 && SwingUtilities.isRightMouseButton(evt);
    }
    /**
      * find Frame/JFrame enclosing a Component/Container/Dialog/Applet... Returns null if can't find one.
     * Useful when you need to pass the enclosing Frame to to a JDialog constructor.
     *
     * @return Frame, will be typically not be a literal Frame, but a
     *         javax.swing.JFrame, sun.applet.AppletViewer, class sun.plugin2.main.client.PluginEmbeddedFrame (For JApplet)
     */
    public static Frame getParentFrame( Component child )
    {
    Container c = child.getParent();
    while ( c != null )
        {
        if ( c instanceof Frame )
            {
            return ( Frame ) c;
            }
        c = c.getParent();
        }
    return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOpcaoAcao;
    private javax.swing.ButtonGroup buttonGroupTipoFiltro;
    private javax.swing.JButton cmdEscolheDiretorio;
    private javax.swing.JButton cmdEscolheDiretorio1;
    private javax.swing.JButton cmdEscolheDiretorio2;
    private javax.swing.JButton cmdIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxCoincidirCaminhoCompleto;
    private javax.swing.JCheckBox jCheckBoxSomenteDiretorios;
    private javax.swing.JEditorPane jEditorPaneResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JRadioButton jRadioButtonAcaoJavascript;
    private javax.swing.JRadioButton jRadioButtonAcaoSubst;
    private javax.swing.JRadioButton jRadioButtonFiltroJavascript;
    private javax.swing.JRadioButton jRadioButtonFiltroRegExp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlbQtdArquivos;
    private javax.swing.JLabel jlbQtdOcorrencias;
    private javax.swing.JLabel jlbQtdPastas;
    private javax.swing.JTextArea txtAcao;
    private javax.swing.JTextArea txtCriterio;
    private javax.swing.JTextField txtDiretorioRaiz;
    // End of variables declaration//GEN-END:variables

    public void run() {
        

    }

    public void onFile(File f) {

        jlbQtdArquivos.setText(
                new Integer(
                    Integer.parseInt(jlbQtdArquivos.getText()) + 1
                ).toString()
        );
    }

    public void onFolder(File f) {
        jlbQtdPastas.setText(
                new Integer(
                    Integer.parseInt(jlbQtdPastas.getText()) + 1
                ).toString()
        );
        //throw new UnsupportedOperationException("Not supported yet.");
    }
    private String DoColor(String s,Color c){
        return "<font color=\"#" +  Integer.toHexString(c.getRGB()).substring(2) + "\">" + s + "</font>";
    }
    public void onMatch(File f) {
        Integer qtdOcu = new Integer(Integer.parseInt(jlbQtdOcorrencias.getText()) + 1);
        if(buttonGroupOpcaoAcao.isSelected(jRadioButtonAcaoSubst.getModel())){
            AcaoSubstituir(f);
        }else{
            AcaoJavascript(f);
        }
        jlbQtdOcorrencias.setText(qtdOcu.toString());
    }

    public void AcaoSubstituir(File f)
    {
        
        String sAcao = txtAcao.getText();
        sAcao = sAcao.replace("\n", "\n<br/>");
        sAcao = sAcao.replace("\b", "&nbsp;");
        sAcao = sAcao.replace("\t", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
        try{
            sAcao = sAcao.replace(FEFITApp.TMPL_CAMINHO, DoColor(f.getCanonicalPath(),Color.RED) ); 
            sAcao = sAcao.replace(FEFITApp.TMPL_PASTA, DoColor( f.getCanonicalFile().getParent(),Color.GREEN) );
        }
        catch(Exception ex)
        {
        }
        sAcao = sAcao 
                .replace(FEFITApp.TMPL_NOME, DoColor(f.getName(),Color.BLUE))
                
                .replace(FEFITApp.TMPL_TAMANHO, DoColor(String.valueOf( f.length() ),Color.ORANGE) );
        
        sb.append(sAcao+"\n<br/>");
        
    }
    public void AcaoJavascript(File f){
        //se.put("f", f);
        //jEditorPaneResultado.setText( "<html><body>" + sb.toString() + "</body></html>");
        //se.put("resultado", jEditorPaneResultado);
        Invocable invo = (Invocable)se;
        try {
            se.eval("function DoWithFile(f){" + txtAcao.getText() + "}");
            sb.append(f.getPath()+"<br/>");
            invo.invokeFunction("DoWithFile", f);
        } catch (Exception ex) {
            Logger.getLogger(JAplFEFIT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
